---
- name: Enable repos
  copy:
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: Install packages for HAProxy
  package:
    name: "{{ haproxy_packages }}"
    state: latest
  notify:
    - Restart HAProxy
    - Enable HAProxy

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - Restart HAProxy
    - Enable HAProxy
