---
- name: Install Active Directory feature
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Configure the Active Directory Domain Controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: win_domain_status

- name: Reboot server
  win_reboot:
    msg: "Installed Active Directory feature"
  when: win_domain_status.reboot_required

- name: List of domains available after reboot
  win_command: nltest /dclist:"{{ ad_domain_name }}"
