---
- name: Enable repos
  copy:
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: Install progress
  package:
    name: "{{ postgres_packages }}"
    state: latest
  notify:
    - Start postgres
    - Enable postgres

- name: Confirm if {{ postgres_data_file }} already exists
  stat:
    path: "{{ postgres_data_file }}"
  register: out

- name: Initilize postgres
  command: postgresql-setup initdb
  when: not out.stat.exists
  notify:
    - Start postgres
    - Enable postgres
