---
- name: Create instances in OpenStack
  os_server:
    name: "{{ item.name }}"
    cloud: ospcloud
    delete_fip: yes
    flavor: "{{ item.flavor }}"
    floating_ip_pools: "{{ item.floating_ip_pools }}"
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    meta: "{{ item.meta }}"
    nics: "{{ item.nics | list }}"
    security_groups: "{{ item.security_groups | list }}"
    state: present
    userdata: "{{ osp_userdata }}"
    wait: yes
  loop: "{{ osp_instances_list }}"
